[package]
name = "dearrow-browser-server"
version.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.2"
actix-web = "4.3.1"
anyhow = "1.0.72"
base64 = "0.21.2"
bitflags = "2.3.3"
chrono = "0.4.26"
dearrow-parser = { path = "../dearrow-parser" }
dearrow-browser-api = { path = "../dearrow-browser-api", features = [ "dearrow-parser" ] }
getrandom = "0.2.10"
serde.workspace = true
toml = "0.7.6"
sha2 = "0.10.7"
