[package]
name = "dearrow-parser"
version.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
bitflags = "2.3.3"
csv = "1.2.2"
serde.workspace = true
